services:
  app:
    extends:
      file: compose.common.yaml
      service: app
    build:
      dockerfile: Dockerfile
    container_name: plane-ticket
    environment:
      - DEPLOY_DATABASE=${DEPLOY_DATABASE:-false}

  db:
    extends:
      file: compose.common.yaml
      service: db
    container_name: plane-ticket-db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
