name: Migration

on:
  workflow_call:

jobs:
  migration:
    name: Migrate and seed database
    runs-on: ubuntu-latest

    env:
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Download deps
        run: npm ci

      - name: Migrate database
        run: npm run db:deploy

      - name: Seed database
        run: npm run db:seed
